### ISSUE TITLE
Support V1.7

### ISSUE THREAD

**Issue by pipinet** [metaloom/qdrant-java-client#16]
```log
2023-12-13 15:02:00,056 ERROR [io.qua.sch.com.run.StatusEmitterInvoker] (mia-vt9) [,] Error occurred while executing task for trigger io.quarkus.quartz.runtime.QuartzSchedulerImpl$QuartzTrigger@49ab7dc9: java.util.concurrent.CompletionException: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)
        at java.base/java.util.concurrent.CompletableFuture$MinimalStage.whenComplete(CompletableFuture.java:2948)
        at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:24)
        at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
        at io.quarkus.scheduler.common.runtime.SkipPredicateInvoker.invoke(SkipPredicateInvoker.java:43)
        at io.quarkus.quartz.runtime.QuartzSchedulerImpl$InvokerJob$1$1.run(QuartzSchedulerImpl.java:888)
        at io.quarkus.virtual.threads.ContextPreservingExecutorService$1.run(ContextPreservingExecutorService.java:36)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
        at hd.mia.infra.qdrant.etl.QdrantCollectionSynchronizer_Subclass.sync(Unknown Source)
        at hd.mia.infra.qdrant.etl.QdrantCollectionSynchronizer_ClientProxy.sync(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at hd.mia.infra.qdrant.etl.QdrantETLWorker.sync(QdrantETLWorker.java:47)
        at hd.mia.infra.qdrant.etl.QdrantETLWorker.lambda$new$0(QdrantETLWorker.java:34)
        at com.qwlabs.lang.LimitedRunner.run(LimitedRunner.java:34)
        at hd.mia.infra.qdrant.etl.QdrantETLWorker.run(QdrantETLWorker.java:39)
        at hd.mia.infra.qdrant.etl.QdrantETLWorker_Subclass.run$$superforward(Unknown Source)
        at hd.mia.infra.qdrant.etl.QdrantETLWorker_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInCallerTx(TransactionalInterceptorBase.java:335)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:40)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at hd.mia.infra.qdrant.etl.QdrantETLWorker_Subclass.run(Unknown Source)
        at hd.mia.infra.qdrant.etl.QdrantETLWorker_ClientProxy.run(Unknown Source)
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
        at hd.mia.core.ai.embedding.storage.EmbeddingStorageETLDispatcher.run(EmbeddingStorageETLDispatcher.java:27)
        at hd.mia.core.ai.embedding.storage.EmbeddingStorageETLDispatcher_ClientProxy.run(Unknown Source)
        at hd.mia.tasks.EmbeddingStorageETLTask.execute(EmbeddingStorageETLTask.java:37)
        at hd.mia.tasks.EmbeddingStorageETLTask_Subclass.execute$$superforward(Unknown Source)
        at hd.mia.tasks.EmbeddingStorageETLTask_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
        at io.quarkus.micrometer.runtime.MicrometerTimedInterceptor.timedMethod(MicrometerTimedInterceptor.java:78)
        at io.quarkus.micrometer.runtime.MicrometerTimedInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at hd.mia.tasks.EmbeddingStorageETLTask_Subclass.execute(Unknown Source)
        at hd.mia.tasks.EmbeddingStorageETLTask_ClientProxy.execute(Unknown Source)
        at hd.mia.tasks.EmbeddingStorageETLTask_ScheduledInvoker_execute_d59d52eff401d7618110096080f239377edcbb79.invokeBean(Unknown Source)
        ... 7 more
Caused by: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
        at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:142)
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:526)
        at com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(GeneratedMessageV3.java:887)
        at io.metaloom.qdrant.client.grpc.proto.Points$PointId$Builder.mergeFrom(Points.java:2496)
        at io.metaloom.qdrant.client.grpc.proto.Points$PointId$1.parsePartialFrom(Points.java:2738)
        at io.metaloom.qdrant.client.grpc.proto.Points$PointId$1.parsePartialFrom(Points.java:2730)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at io.metaloom.qdrant.client.grpc.proto.Points$PointId.parseFrom(Points.java:2261)
        at hd.mia.infra.qdrant.QdrantHelper.pointId(QdrantHelper.java:14)
        at hd.mia.infra.qdrant.etl.QdrantCollectionSynchronizer.of(QdrantCollectionSynchronizer.java:97)
        at hd.mia.infra.qdrant.etl.QdrantCollectionSynchronizer.lambda$sync$0(QdrantCollectionSynchronizer.java:71)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1858)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at hd.mia.infra.qdrant.etl.QdrantCollectionSynchronizer.sync(QdrantCollectionSynchronizer.java:75)
        at hd.mia.infra.qdrant.etl.QdrantCollectionSynchronizer.sync(QdrantCollectionSynchronizer.java:50)
        at hd.mia.infra.qdrant.etl.QdrantCollectionSynchronizer_Subclass.sync$$superforward(Unknown Source)
        at hd.mia.infra.qdrant.etl.QdrantCollectionSynchronizer_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.micrometer.runtime.binder.mpmetrics.TimedInterceptor.time(TimedInterceptor.java:48)
        at io.quarkus.micrometer.runtime.binder.mpmetrics.TimedInterceptor.timedMethod(TimedInterceptor.java:34)
        at io.quarkus.micrometer.runtime.binder.mpmetrics.TimedInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        ... 66 more
```

**Comment by Jotschi** [comment]
Only v1.2.0 is currently supported.
